export const HABIT_DEFINITIONS = [
  {
    key: 'jobs_applied',
    streakKey: 'jobs',
    name: 'Job Applications',
    description: 'Applied to 5+ jobs today',
    icon: '💼',
    stripLabel: 'Jobs',
  },
  {
    key: 'recruiters_contacted',
    streakKey: 'recruiters',
    name: 'Recruiter Outreach',
    description: 'Reached out to 2+ recruiters/HMs today',
    icon: '📬',
    stripLabel: 'Outreach',
  },
  {
    key: 'product_walkthrough',
    streakKey: 'product_walkthrough',
    name: 'Product Walkthrough',
    description: 'Reviewed a Product walkthrough case today',
    icon: '📖',
    stripLabel: 'PM Walk',
  },
  {
    key: 'product_practiced',
    streakKey: 'product',
    name: 'Product Practice',
    description: 'Completed a live Product case practice session',
    icon: '🧠',
    stripLabel: 'PM Pract',
  },
  {
    key: 'tpm_walkthrough',
    streakKey: 'tpm_walkthrough',
    name: 'TPM Walkthrough',
    description: 'Reviewed a TPM walkthrough case today',
    icon: '🛠️',
    stripLabel: 'TPM Walk',
  },
  {
    key: 'tpm_practiced',
    streakKey: 'tpm',
    name: 'TPM Practice',
    description: 'Completed a live TPM case practice session',
    icon: '⚙️',
    stripLabel: 'TPM Pract',
  },
];

export const HEATMAP_COLORS = {
  0: '#ebedf0',
  1: '#e2f4c5',
  2: '#c6e48b',
  3: '#7bc96f',
  4: '#239a3b',
  5: '#196127',
  6: '#0f441c',
};
